language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - python setup.py install

# command to run tests
script:
  - python -m unittest discover -s tests -p "test_*.py"
